version: '3.7'
services:
  api:
    build:
      context: ./server
      dockerfile: ./Dockerfile.develop
    tty: true
    stdin_open: true
    volumes:
      - ./server:/usr/app
    environment:
      - TZ=Asia/Tokyo
      - MONGO_URL=mongodb://react-user:passw0rd@mongo:27017/react-sample
    ports:
      - '3000:3000'
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: react-sample
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - ./docker_configs/db/init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro